import { spawnSync } from 'node:child_process';
import { mkdir, readFile, writeFile, appendFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createEvidenceBinding, createCandidateFingerprint, hashPaths } from './evidence-binding.mjs';
import { loadArchitectureState } from './architecture-state.mjs';
import { validateImpactPolicy, minimizeProfiles, isProofInput, requiresRuntimeProof } from './impact-routing.mjs';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);

function valueAfter(flag) {
    const index = args.indexOf(flag);
    return index >= 0 ? args[index + 1] : null;
}

function git(gitArgs) {
    const result = spawnSync('git', gitArgs, { cwd: rootDir, encoding: 'utf8' });
    if (result.status !== 0) throw new Error(result.stderr.trim() || `git ${gitArgs.join(' ')} failed`);
    return result.stdout.trim();
}

function normalize(file) {
    return file.replace(/\\/g, '/').replace(/^\.\//, '');
}

function matches(reference, file) {
    const normalizedReference = normalize(reference);
    const normalizedFile = normalize(file);
    if (!normalizedReference.includes('*')) return normalizedReference === normalizedFile;
    const escaped = normalizedReference.split('**').map(part => part.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '[^/]*')).join('.*');
    return new RegExp(`^${escaped}$`).test(normalizedFile);
}

const gatesBytes = await readFile(path.join(rootDir, 'verification', 'gates.json'));
const architectureState = await loadArchitectureState(rootDir);
if (architectureState.candidateFailures.length) {
    throw new Error(`Invalid architecture candidate:\n${architectureState.candidateFailures.join('\n')}`);
}
const registry = architectureState.effective;
const gates = JSON.parse(gatesBytes);
validateImpactPolicy(registry, gates);
const targets = JSON.parse(await readFile(path.join(rootDir, 'build/targets.json'), 'utf8')).targets;
const worktree = args.includes('--worktree');
const head = valueAfter('--head') || 'HEAD';
const base = valueAfter('--base') || (worktree ? head : `${head}^`);
const explicitFiles = valueAfter('--files');
if (worktree && explicitFiles) throw new Error('--worktree and --files cannot be combined');
const full = args.includes('--full');
const worktreeExclusions = [
    /^(?:artifacts|dist|testbed\/artifacts|verification\/receipts)\//,
    /^(?:Dc_UserFilter_Mobile_v[^/]+|dcinside_user_filter_v[^/]+)\.user\.js$/,
    /^debug\.log$/,
];
const worktreeFiles = () => [...new Set([
    ...git(['diff', '--name-only', '-z']).split('\0'),
    ...git(['diff', '--cached', '--name-only', '-z']).split('\0'),
    ...git(['ls-files', '--others', '--exclude-standard', '-z']).split('\0'),
].map(normalize).filter(Boolean).filter((file) => !worktreeExclusions.some((pattern) => pattern.test(file))))].sort();
const changedFiles = explicitFiles
    ? explicitFiles.split(',').map(normalize).filter(Boolean)
    : worktree
        ? worktreeFiles()
        : git(['diff', '--name-only', `${base}...${head}`]).split(/\r?\n/).map(normalize).filter(Boolean);
const selectedComponents = new Set();
const selectedProfiles = new Set(['policy']);
const unmappedFiles = [];
const generatedFiles = [];
const runtimeFiles = changedFiles.filter(file => file.startsWith('src/'));
const headerScope = gates.boundedScopes['header-navigation'];
const boundedScope = !full && runtimeFiles.length > 0
    && runtimeFiles.every(file => headerScope.sourcePaths.includes(file))
    && changedFiles.every(file => /^(?:src|docs)\//.test(file) || file === 'AGENTS.md')
    ? 'header-navigation' : null;

for (const file of changedFiles) {
    const generatedTarget = Object.entries(targets).find(([, target]) => {
        const name = target.outputPattern.replace('{version}', target.version);
        return file === name || file === `dist/${name}`;
    })?.[0];
    if (generatedTarget) {
        generatedFiles.push({ path: file, target: generatedTarget });
        // Generated bytes are still checked against their canonical builder, never silently ignored.
        selectedProfiles.add('acceptance');
        continue;
    }
    if (isProofInput(file)) selectedProfiles.add('proof-core');
    if (requiresRuntimeProof(file)) selectedProfiles.add('proof-runtime');
    if (/^docs\/work\/(?:CURRENT_STATE|NEXT_TASK)\.md$/.test(file)) continue;
    const matchesForFile = registry.components.filter((component) => component.sourceRefs.some((reference) => matches(reference, file)));
    if (matchesForFile.length) {
        for (const component of matchesForFile) selectedComponents.add(component.id);
        continue;
    }
    if (file === 'AGENTS.md' || /^(architecture|verification|vendor|\.agents)\//.test(file)) {
        selectedComponents.add('architecture-governance');
    } else if (/^(build|tools)\//.test(file)) {
        selectedProfiles.add('acceptance');
        unmappedFiles.push(file);
    } else if (/^docs\//.test(file)) {
        selectedProfiles.add(file === 'docs/ui-surface-contracts.md' ? 'mobile-focused' : 'policy');
    } else {
        selectedProfiles.add(gates.fallbackProfile);
        unmappedFiles.push(file);
    }
}

const queue = [...selectedComponents];
while (queue.length) {
    const componentId = queue.shift();
    for (const relation of registry.relations.filter((item) => item.from === componentId)) {
        if (gates.relationImpact[relation.kind] !== 'runtime') continue;
        if (!selectedComponents.has(relation.to)) {
            selectedComponents.add(relation.to);
            queue.push(relation.to);
        }
    }
}

for (const componentId of selectedComponents) {
    const component = registry.components.find((item) => item.id === componentId);
    const verificationOnly = component?.layer === 'verification';
    const componentProfiles = boundedScope && !verificationOnly ? [headerScope.profile]
        : gates.componentProfiles[componentId] || [gates.fallbackProfile];
    for (const profile of componentProfiles) selectedProfiles.add(profile);
    for (const invariantId of component?.fitnessRefs || []) {
        for (const profile of gates.invariantProfiles?.[invariantId] || []) {
            // A verification constraint does not mutate the runtime it describes.
            if (verificationOnly && !['policy', 'proof-core', 'proof-runtime'].includes(profile)) continue;
            selectedProfiles.add(boundedScope && !verificationOnly && profile !== 'policy' ? headerScope.profile : profile);
        }
    }
}
if (full) for (const profile of ['acceptance', 'proof-core', 'proof-runtime']) selectedProfiles.add(profile);

const profiles = minimizeProfiles(selectedProfiles, gates);
const receipt = {
    schemaVersion: 2,
    routeSource: explicitFiles ? 'explicit-files' : worktree ? 'worktree' : 'git-diff',
    full,
    base: git(['rev-parse', base]),
    head: git(['rev-parse', head]),
    candidateFingerprint: worktree ? await createCandidateFingerprint(rootDir) : null,
    continuitySha256: worktree ? await hashPaths(rootDir, ['docs/work/CURRENT_STATE.md', 'docs/work/NEXT_TASK.md']) : null,
    changedFiles,
    generatedFiles,
    boundedScope,
    selectedComponents: [...selectedComponents].sort(),
    selectedProfiles: profiles,
    resolvedCommands: profiles.flatMap((profile) => (gates.profiles[profile]?.commands || []).map((item) => ({ profile, ...item }))),
    unmappedFiles: [...new Set(unmappedFiles)].sort(),
    evidenceBinding: await createEvidenceBinding(rootDir),
};

const output = valueAfter('--output');
if (output) {
    const outputPath = path.resolve(rootDir, output);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, `${JSON.stringify(receipt, null, 2)}\n`, 'utf8');
}
const ciOutput = valueAfter('--ci-output');
if (ciOutput) {
    const values = {
        acceptance: profiles.includes('acceptance'),
        focused: profiles.some(profile => ['header-focused', 'mobile-focused', 'pc-focused'].includes(profile)),
        proofRuntime: profiles.includes('proof-runtime'),
    };
    await appendFile(ciOutput, Object.entries(values).map(([key, value]) => `${key}=${value}\n`).join(''), 'utf8');
}
process.stdout.write(`${JSON.stringify(receipt, null, 2)}\n`);
